### ISSUE TITLE
[DOC] Adding minimal working examples to docstrings; a checklist

### ISSUE THREAD

**Issue by thatlittleboy** [pyjanitor-devs/pyjanitor#972]
## Background

This thread is borne out of the discussion from #968 , in an effort to make documentation more beginner-friendly & more understandable.
One of the subtasks mentioned in that thread was to go through the function docstrings and include a *minimal* working example to each of the public functions in pyjanitor.

Criteria reiterated here for the benefit of discussion:

>     It should fit with our existing choice to go with mkdocs, mkdocstrings, and mknotebooks.
>     The examples should be minimal and executable and complete execution within 5 seconds per function.
>     The examples should display in rich HTML on our docs page.
>     We should have an automatic way of identifying whether a function has an example provided or not so that every function has an example.

Sample of what MWE should look like is shown [here](https://github.com/pyjanitor-devs/pyjanitor/issues/968#issuecomment-1003672331).

---

I'm thinking we can create a task list so that 1. we can encourage more users to join in the effort, and 2. make sure we don't do duplicate work. A lot of the groundwork can be covered by selectively copying one or two examples over from the software test suite.

Then we can label this issue as a Help Wanted / Low-Hanging Fruit and get people to mention in this thread if they're intending to work on the files?

### Task list

- [X] functions/add_columns.py
- [x] functions/also.py
- [x] functions/bin_numeric.py
- [x] functions/case_when.py
- [x] functions/change_type.py
- [x] functions/clean_names.py
- [x] functions/coalesce.py
- [x] functions/collapse_levels.py
- [x] functions/complete.py
- [x] functions/concatenate_columns.py
- [x] functions/conditional_join.py
- [x] functions/convert_date.py
- [x] functions/count_cumulative_unique.py
- [x] functions/currency_column_to_numeric.py
- [x] functions/deconcatenate_column.py
- [x] functions/drop_constant_columns.py
- [x] functions/drop_duplicate_columns.py
- [x] functions/dropnotnull.py
- [x] functions/encode_categorical.py
- [x] functions/expand_column.py
- [x] functions/expand_grid.py
- [x] functions/factorize_columns.py
- [x] functions/fill.py
- [x] functions/filter.py
- [x] functions/find_replace.py
- [x] functions/flag_nulls.py
- [x] functions/get_dupes.py
- [x] functions/groupby_agg.py
- [x] functions/groupby_topk.py
- [x] functions/impute.py
- [x] functions/jitter.py
- [x] functions/join_apply.py
- [x] functions/label_encode.py
- [x] functions/limit_column_characters.py
- [x] functions/min_max_scale.py
- [x] functions/move.py
- [x] functions/pivot.py
- [x] functions/process_text.py
- [x] functions/remove_columns.py
- [x] functions/remove_empty.py
- [x] functions/rename_columns.py
- [x] functions/reorder_columns.py
- [x] functions/round_to_fraction.py
- [x] functions/row_to_names.py
- [x] functions/select_columns.py
- [x] functions/shuffle.py
- [x] functions/sort_column_value_order.py
- [x] functions/sort_naturally.py
- [x] functions/take_first.py
- [x] functions/then.py
- [x] functions/to_datetime.py
- [x] functions/toset.py
- [x] functions/transform_columns.py
- [x] functions/truncate_datetime.py
- [x] functions/update_where.py
- [ ] spark/backend.py
- [ ] spark/functions.py
- [x] xarray/functions.py
- [x] biology.py
- [x] chemistry.py
- [x] engineering.py
- [ ] errors.py
- [x] finance.py
- [x] io.py
- [x] math.py
- [x] ml.py
- [x] timeseries.py
B

**Comment by thatlittleboy** [comment]
- `functions/bin_numeric.py` is already in PR

I'm currently having a look at
- `functions/rename_columns.py`
- `functions/reorder_columns.py`
- `functions/to_datetime.py`
- `functions/also.py`
- `functions/then.py`
- `functions/dropnotnull.py`
- `functions/groupby_agg.py`
- `functions/flag_nulls.py`

Will probably look at some more as and when I have time over the next week or so

**Comment by ericmjl** [comment]
This is awesome, @thatlittleboy! Thank you for handling this here :smile:. I've invited you to the dev team to help move this along.

**Comment by ericmjl** [comment]
One trick I'm finding is that it's pretty easy to create a minimal working example from the test suite :joy_cat:.

**Comment by thatlittleboy** [comment]
Ongoing sprint, dibs on the following:
* `functions/change_type.py`
* `functions/coalesce.py`
* `functions/collapse_levels.py`
* `functions/filter.py`

**Comment by ericmjl** [comment]
Same here, dibs on:

* `functions/take_first.py`
* `functions/sort_naturally.py`

**Comment by ericmjl** [comment]
Dibs on:

- functions/min_max_scale.py
- functions/move.py

Two per PR seems to be the load that I personally can handle :joy_cat:.

**Comment by thatlittleboy** [comment]
Ongoing sprint:
* `functions/concatenate_columns.py`
* `functions/deconcatenate_column.py`
* `functions/select_columns.py`

**Comment by ericmjl** [comment]
Going to work on:

- `functions/drop_constant_columns.py`
- `functions/drop_duplicate_columns.py`

**Comment by thatlittleboy** [comment]
Ongoing sprint:
- `functions/move.py`
- `functions/remove_columns.py`
- `functions/remove_empty.py`
- `functions/limit_column_characters.py`

**Comment by thatlittleboy** [comment]
Ongoing sprint:
- `functions/round_to_fraction.py`
- `functions/row_to_names.py`
- `functions/shuffle.py`

**Comment by thatlittleboy** [comment]
Currently looking at:

- functions/impute.py
- functions/jitter.py
- functions/join_apply.py

Also in the midst of updating:
- functions/encode_categorical.py
- functions/label_encode.py
- functions/factorize_columns.py

**Comment by apatao** [comment]
hi - this is amie from pycon 2022 sprints, i am claiming:
 functions/convert_date.py

**Comment by gahjelle** [comment]
Hey, I'm Geir Arne @ the PyCon US 2022 sprints.

I'm claiming `functions/expand_column.py` to work on.

**Comment by catherinedevlin** [comment]
It's Catherine Devlin at PyCon 2022!

I'll start on chemistry.py.

**Comment by SamBauter** [comment]
Pycon 2022 - working on timeseries.py

**Comment by gahjelle** [comment]
I'll also do `functions/find_replace.py`

**Comment by ghost** [comment]
I'll do functions/fill.py

**Comment by ethompsy** [comment]
Pycon 2022 - working on `functions/get_dupes.py`

**Comment by ethompsy** [comment]
Pycon 2022 - working on `functions/groupby_topk.py`

**Comment by gahjelle** [comment]
I'll do `math.py`

**Comment by ghost** [comment]
Dibs on `functions/transform_columns.py`

**Comment by catherinedevlin** [comment]
For my next trick, I'd like to do biology.py

**Comment by ghost** [comment]
It looks like `transform_columns.py` is already done :(

Dibs on `update_where.py`

**Comment by dancassin** [comment]
Dibs on finance.py

**Comment by gahjelle** [comment]
I'll do `ml.py` next

**Comment by gahjelle** [comment]
I'll do `xarray/functions.py`

**Comment by catherinedevlin** [comment]
In honor of my favorite Jovian moon, I'd like to do io.py next.  (It looks almost done already, but there are still a couple non-doctest)

**Comment by Zeroto521** [comment]
`functions/min_max_scale.py` done via #1107 and #1112
